import {StyleSheet, Dimensions} from 'react-native';
const devicesSize = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    backgroundColor: '#E3DFFD',
    flex: 1,
  },
  flatlistcontainer: {
    backgroundColor: '#ECF2FF',
    marginTop: 10,
    marginLeft: 20,
    marginRight: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    flex: 0.95,
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.5,
    shadowRadius: 3,
    elevation: 20,
  },
  button: {
    backgroundColor: '#c9dff1',
    width: devicesSize.width / 1.7,
    height: devicesSize.height / 6.5,
    borderRadius: 30,
    alignItems: 'center',
    //justifyContent: 'center',
    marginTop: 40,
    shadowColor: 'grey',
    shadowOffset: {height: 4},
    shadowOpacity: 0.5,
    shadowRadius: 1,
  },
  imagecontainer: {
    width: '100%',
    //backgroundColor: 'red',
    //height: 80,
    flex: 1,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
  },
  image: {
    width: '100%',
    height: '100%',
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
  },
  titlecontainer: {
    alignItems: 'center',
    justifyContent: 'center',
    //backgroundColor: 'green',
    //width: '100%',
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
  },
  title: {
    fontSize: devicesSize.width / 31,
    fontWeight: 'bold',
    color: 'black',
  },
});
