import {StyleSheet, Dimensions} from 'react-native';
const devicesSize = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    backgroundColor: 'rgba(255, 255,255, 0)',
    alignItems: 'flex-start',
    //justifyContent: 'center',
    marginRight: 30,
    marginLeft: 0,
    height: 400,
    borderRadius: 30,
    marginTop: -230,
  },
  buttoncontainer: {
    width: '100%',
    height: 40,
    //backgroundColor: 'red',
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
  },
  button: {
    width: 80,
    height: 40,
    backgroundColor: '#8F43EE',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    marginRight: 10,
    shadowColor: '#171717',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },
  buttontitle: {
    fontWeight: 'bold',
    color: 'white',
  },
  imagecontainer: {
    //backgroundColor: 'red',
    width: '100%',
    height: '30%',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  image: {
    width: 150,
    height: 100,
    resizeMode: 'contain',
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.5,
    shadowRadius: 3,
    marginLeft: 50,
  },
  infocontainer: {
    backgroundColor: 'rgba(255, 255,255, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    marginTop: 50,
    width: '100%',
    marginLeft: 10,
  },
  info: {
    fontWeight: 'bold',
    fontSize: 30,
    textAlign: 'center',
    color: 'black',
  },
});
